# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='myinfo.proto',
  package='com.xiaoming.protobuf',
  serialized_pb=_b('\n\x0cmyinfo.proto\x12\x15\x63om.xiaoming.protobuf\"\xfd\x01\n\tClassMate\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12;\n\x05phone\x18\x04 \x03(\x0b\x32,.com.xiaoming.protobuf.ClassMate.PhoneNumber\x1a]\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x02(\t\x12>\n\x04type\x18\x02 \x02(\x0e\x32*.com.xiaoming.protobuf.ClassMate.PhoneType:\x04HOME\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\"<\n\nAlumniBook\x12.\n\x04mate\x18\x01 \x03(\x0b\x32 .com.xiaoming.protobuf.ClassMate')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CLASSMATE_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='com.xiaoming.protobuf.ClassMate.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=250,
  serialized_end=293,
)
_sym_db.RegisterEnumDescriptor(_CLASSMATE_PHONETYPE)


_CLASSMATE_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='com.xiaoming.protobuf.ClassMate.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='com.xiaoming.protobuf.ClassMate.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.xiaoming.protobuf.ClassMate.PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=248,
)

_CLASSMATE = _descriptor.Descriptor(
  name='ClassMate',
  full_name='com.xiaoming.protobuf.ClassMate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.xiaoming.protobuf.ClassMate.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='com.xiaoming.protobuf.ClassMate.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='com.xiaoming.protobuf.ClassMate.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='com.xiaoming.protobuf.ClassMate.phone', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CLASSMATE_PHONENUMBER, ],
  enum_types=[
    _CLASSMATE_PHONETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=293,
)


_ALUMNIBOOK = _descriptor.Descriptor(
  name='AlumniBook',
  full_name='com.xiaoming.protobuf.AlumniBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mate', full_name='com.xiaoming.protobuf.AlumniBook.mate', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=355,
)

_CLASSMATE_PHONENUMBER.fields_by_name['type'].enum_type = _CLASSMATE_PHONETYPE
_CLASSMATE_PHONENUMBER.containing_type = _CLASSMATE
_CLASSMATE.fields_by_name['phone'].message_type = _CLASSMATE_PHONENUMBER
_CLASSMATE_PHONETYPE.containing_type = _CLASSMATE
_ALUMNIBOOK.fields_by_name['mate'].message_type = _CLASSMATE
DESCRIPTOR.message_types_by_name['ClassMate'] = _CLASSMATE
DESCRIPTOR.message_types_by_name['AlumniBook'] = _ALUMNIBOOK

ClassMate = _reflection.GeneratedProtocolMessageType('ClassMate', (_message.Message,), dict(

  PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), dict(
    DESCRIPTOR = _CLASSMATE_PHONENUMBER,
    __module__ = 'myinfo_pb2'
    # @@protoc_insertion_point(class_scope:com.xiaoming.protobuf.ClassMate.PhoneNumber)
    ))
  ,
  DESCRIPTOR = _CLASSMATE,
  __module__ = 'myinfo_pb2'
  # @@protoc_insertion_point(class_scope:com.xiaoming.protobuf.ClassMate)
  ))
_sym_db.RegisterMessage(ClassMate)
_sym_db.RegisterMessage(ClassMate.PhoneNumber)

AlumniBook = _reflection.GeneratedProtocolMessageType('AlumniBook', (_message.Message,), dict(
  DESCRIPTOR = _ALUMNIBOOK,
  __module__ = 'myinfo_pb2'
  # @@protoc_insertion_point(class_scope:com.xiaoming.protobuf.AlumniBook)
  ))
_sym_db.RegisterMessage(AlumniBook)


# @@protoc_insertion_point(module_scope)
